### ISSUE TITLE
设备中心；停留在第二页的时候，自动刷新完，回到了第一页

### ISSUE THREAD

**Issue by Github-KaibinHuang** [SonicCloudOrg/sonic-server-simple#36]
设备中心；停留在第二页的时候，自动刷新完，回到了第一页

**Comment by ZhouYixun** [comment]
已知问题，跟这个重复了https://github.com/SonicCloudOrg/sonic-client-web/issues/75 后续修复进度可以在那边看到，我先关闭这个issue~感谢关注
