### ISSUE TITLE
能设置关闭注册功能吗？

### ISSUE THREAD

**Issue by liangjaden** [SonicCloudOrg/sonic-server-simple#80]
目前平台是只要知道平台登录地址就能任意注册后登入操控，这很不安全，但后台并没有注册相关的设置

**Comment by ZhouYixun** [comment]
> 目前平台是只要知道平台登录地址就能任意注册后登入操控，这很不安全，但后台并没有注册相关的设置

已经做了，下版本再放出，后续留意更新信息把
